### PR TITLE
Issue 3 contribution

### PR DESCRIPTION
**Pull request by l0010o0001l**
lub u all ~

### CODE REVIEW

**Comment by MineRobber9000** [comment]
Sadly, Issue 2 has been finalized. Please resubmit your contribution for issue 3.

**Comment by MineRobber9000** [comment]
The issue 3 directory has been created. Sorry for missing you with our wonky release schedule.

**Comment by MineRobber9000** [comment]
Basically, move `issue_2/contrived.jpg` to `issue_3/contrived.jpg` and your submission will be accepted.

**Comment by l0010o0001l** [comment]
👍  donezo

**Comment by MineRobber9000** [comment]
heck yes thanks

**Comment by MineRobber9000** [comment]
as a prize, you get access to the repo (so you can merge PRs)

**Comment by fonorobert** [comment]
yay, first contribution to issue 3 🙌

**Comment by l0010o0001l** [comment]
wheeeee

**Pull request merged**
